import dayjs from 'dayjs'
import type { ITask } from '@/shared/types/task.types.ts'

export const mockTasks: ITask[] = [
  {
    id: '1',
    label: 'Morning Routine',
    description: 'desc',
    tagValue: 'personal',
    timeRange: [dayjs('0:45', 'HH:mm'), dayjs('1:45', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '3',
    label: 'Evening Routine',
    description: 'desc',
    tagValue: 'health',
    timeRange: [dayjs('1:45', 'HH:mm'), dayjs('2:30', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '2',
    label: 'Day Routine',
    description: 'desc',
    tagValue: 'business',
    timeRange: [dayjs('2:30', 'HH:mm'), dayjs('3:15', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '4',
    label: 'RoutineRoutine Routine ',
    description: 'desc',
    tagValue: 'health',
    timeRange: [dayjs('3:15', 'HH:mm'), dayjs('3:45', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '5',
    label: 'Night',
    description: 'desc',
    tagValue: 'work',
    timeRange: [dayjs('3:45', 'HH:mm'), dayjs('4:00', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '11111',
    label: '111Morning Routine111',
    description: '111desc111',
    tagValue: 'study',
    timeRange: [dayjs('1:00', 'HH:mm'), dayjs('5:00', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '11311',
    label: '111Evening Routine111',
    description: '111desc111',
    tagValue: 'health',
    timeRange: [dayjs('11:45', 'HH:mm'), dayjs('12:30', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '11211',
    label: '111Day Routine111',
    description: '111desc111',
    tagValue: 'business',
    timeRange: [dayjs('11:15', 'HH:mm'), dayjs('13:00', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '11411',
    label: '111Routine111',
    description: '111desc111',
    tagValue: 'health',
    timeRange: [dayjs('11:00', 'HH:mm'), dayjs('12:30', 'HH:mm')],
    date: dayjs(),
  },
  {
    id: '11511',
    label: '111Night111',
    description: '111desc111',
    tagValue: 'work',
    timeRange: [dayjs('12:30', 'HH:mm'), dayjs('13:30', 'HH:mm')],
    date: dayjs(),
  },
]
